spring:  
  datasource:  
    url : jdbc:mysql://106.75.66.135:3306/thingshub
    username : admin
    password : "admin$mfwifi#2016!"
    driverClassName : com.mysql.jdbc.Driver
    
    
mybatis:
  config-locations: "classpath*:mybatis-config.xml"
  mapper-locations: "classpath*:mapper/*.xml"